services:
  app:
    image: golang:1.18-alpine
    command: sh -c "go build -o bin/server/litesite cmd/server/main.go && /app/bin/server/litesite"
    ports:
      - 5050:5050
    working_dir: /app
    volumes: 
      - ./:/app
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    volumes:
      - ./.docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - site-mysql-data:/var/lib/mysql
    env_file:
      - .env
  flyway:
    platform: ${PLATFORM}
    command: -url=jdbc:mysql://mysql/${MYSQL_DB}?allowPublicKeyRetrieval=true migrate
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    depends_on:
      - mysql
volumes: 
  site-mysql-data: